@baseUrl = http://localhost:3000

### Find Users
GET {{baseUrl}}/users


### Create an User
POST {{baseUrl}}/users
Content-Type: application/json

{
    "name": "Alvaro",
    "email": "alvaro.veloz@gmail.com",
    "password": "123456"
}
