version: '3.8'

services:
  db:
    image: postgres:13.3
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: nest
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
